### ISSUE TITLE
Screen showing black!

### ISSUE THREAD

**Issue by kaushik-mota** [Mapwize/mapwize-simple-app-android#1]
I am trying to run this app and getting weird issue of black screen .
I have added API KEY in `MapwizeSimpleApplication` class as well.

**UI issue :**
![device-2018-09-24-185102](https://user-images.githubusercontent.com/10348357/45954409-95d93680-c02a-11e8-8af6-c45a614fc11b.png)

**API Key Added :**
![img-2018-09-24_18 47 25](https://user-images.githubusercontent.com/10348357/45954491-c620d500-c02a-11e8-868b-d4e8d1aae564.png)

**Device Information:**
![device-2018-09-24-180006](https://user-images.githubusercontent.com/10348357/45954431-a4275280-c02a-11e8-9960-0e3f8c72a0e7.png)

**Comment by santoki-darshan** [comment]
Same issue to me, getting below error in log
**{mpleapplication}[Setup]: loading style failed: HTTP status code 403**

**Comment by emerciercontexeo** [comment]
Did you set the api key in the activity_main.xml ?

Actually, you have to set ApiKey in Application class and in the layout file.
app:mapbox_styleUrl="https://outdoor.mapwize.io/styles/mapwize/style.json?key=YOU_MAPWIZE_API_KEY"/>

This allows mapbox sdk to load our map style.

I know that is not really developer friendly but I am working on it.

**Comment by santoki-darshan** [comment]
Actually, I was following [documentation](https://docs.mapwize.io/doc/android/1.6.0/) and setting api key in xml is not mentioned there.

**Comment by emerciercontexeo** [comment]
Take a look at the "Configuring the outdoor map" part in this documentation :)

I will add information in the README of our public project to simplify first tests

**Comment by kaushik-mota** [comment]
Thank you for the help, @emerciercontexeo !
